INSERT INTO dog (id, name, breed, origin) VALUES (1, 'Fluffy', 'Pomeranian', 'Mountain View, CA');
INSERT INTO dog (id, name, breed, origin) VALUES (2, 'Spot', 'Pit Bull', 'Austin, TX');
INSERT INTO dog (id, name, breed, origin) VALUES (3, 'Ginger', 'Cocker Spaniel', 'Kansas City, KS');
INSERT INTO dog (id, name, breed, origin) VALUES (4, 'Lady', 'Direwolf', 'The North');
INSERT INTO dog (id, name, breed, origin) VALUES (5, 'Sasha', 'Huskdy', 'Buffalo, NY');
INSERT INTO dog (id, name, breed, origin) VALUES (6, 'CESasha', 'Hussky', 'Buffalo, NY');
INSERT INTO dog (id, name, breed, origin) VALUES (7, 'SWQasha', 'Hucsky', 'Buffalo, NY');
INSERT INTO dog (id, name, breed, origin) VALUES (8, 'fdeE', 'Huskfy', 'Buffalo, NY');
INSERT INTO dog (id, name, breed, origin) VALUES (9, 'BERSdfsfe', 'Huseky', 'Buffalo, NY');
INSERT INTO dog (id, name, breed, origin) VALUES (10, 'SEWvr rasha', 'Hussky', 'Buffalo, NY');
INSERT INTO dog (id, name, breed, origin) VALUES (11, 'SCreasha', 'Husky', 'Buffalo, NY');